# Demographic Data Analyzer

In [ ]:
import pandas as pd

In [ ]:
# Read data from file
df = pd.read_csv('adult.data.csv')

In [ ]:
# How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
df.groupby('race')['race'].count()

race
Amer-Indian-Eskimo      311
Asian-Pac-Islander     1039
Black                  3124
Other                   271
White                 27816
Name: race, dtype: int64

In [ ]:
 # What is the average age of men?
 round(df[df['sex']=='Male']['age'].mean(), 1)

39.4

In [ ]:
# What is the percentage of people who have a Bachelor's degree?
round(df[df['education'] == 'Bachelors'].shape[0] / df.shape[0] * 100, 1)

16.4

In [ ]:
# What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
# What percentage of people without advanced education make more than 50K?

salary1 = df['education'].isin(['Bachelors', ' Masters', 'Doctorate'])
salary2 = df['salary'] == '>50K'

higher_edu_and_rich = round((salary1 & salary2).sum() / salary1.sum() * 100 , 1)
lower_edu_and_rich = round(((~salary1) & (salary2)).sum() / (~salary1).sum() * 100, 1)

print(higher_edu_and_rich)
print(lower_edu_and_rich)

43.8
19.8

In [ ]:
 # What is the minimum number of hours a person works per week (hours-per-week feature)?
 df['hours-per-week'].min()

1

In [ ]:
# What percentage of the people who work the minimum number of hours per week have a salary of >50K?
min_work_hours = df['hours-per-week'].min()
q1 = df['hours-per-week'] == min_work_hours
q2 = df['salary'] == '>50K'
round((q1 & q2).sum() / q1.sum() * 100 , 1)

10.0

In [ ]:
# What country has the highest percentage of people that earn >50K?
country_fifty_K = (df[q2]['native-country'].value_counts() /
                   df['native-country'].value_counts() * 100 ).sort_values(ascending = False)
print(country_fifty_K.index[0])
print(round(country_fifty_K.iloc[0], 1))

Iran
41.9

In [ ]:
 # Identify the most popular occupation for those who earn >50K in India
df[(df['native-country'] == 'India') & q2]['occupation'].value_counts().index[0]

'Prof-specialty'